# This is a basic workflow to help you get started with Actions

name: CTP CI/CD Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Custom environment variables declared in workflow level
env:
  CTP_URL: http://34.221.143.134:8080/em/
  DTP_URL: http://18.236.243.147:8080/grs/
  USERNAME: demo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - uses: parasoft/execute-job-action@1.0.4
        with:
          ctpUrl: ${ CTP_URL }
          ctpUsername: ${ USERNAME }
          ctpPassword: ${{ secrets.PASSWORD }}
          ctpJob: 'P1 Smoke Tests'
