# This is a basic workflow to help you get started with Actions

name: CTP CI/CD Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Custom environment variables declared in workflow level
env:
  CTP_URL: http://34.221.143.134:8080/em/
  DTP_URL: http://18.236.243.147:8080/grs/
  USERNAME: demo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Deploy an environment in CTP
      - name: Deploy an environment in CTP
        uses: parasoft/deploy-environment-action@v1
        with:
          ctpUrl: ${{ env.CTP_URL }}
          ctpUsername: ${{ env.USERNAME }}
          ctpPassword: ${{ secrets.PASSWORD }}
          system: 'ParaBank'
          environment: 'Retail Services (Silo 1)'
          instance: 'Positive'

      # Execute a job in CTP
      - name: Execute a job in CTP
        uses: parasoft/execute-job-action@v1
        with:
          ctpUrl: ${{ env.CTP_URL }}
          ctpUsername: ${{ env.USERNAME }}
          ctpPassword: ${{ secrets.PASSWORD }}
          ctpJob: 'P1 Smoke Tests'
          publishReport: true
          dtpUrl: ${{ env.DTP_URL }}
          dtpUsername: ${{ env.USERNAME }}
          dtpPassword: ${{ secrets.password }}
          dtpProject: 'Parabank_Master'
          buildId: ${{ github.run_number }}
          sessionTag: ${{ github.workflow }}
          appendEnvironment: false
